### ISSUE TITLE
No module named 'datapreparation.kitti360' when loading the data

### ISSUE THREAD

**Issue by tdzdog** [mako443/Text2Pos-CVPR2022#2]
The sub-directory has been changed to 'kitti360pose' while the data is generated with 'kitti360'. Hence the error occurs during loading the data by pickle.

**Comment by mako443** [comment]
Hi @tdzdog, thank you for pointing that out and sorry for the inconvenience.
I have just pushed a temporary fix using the `dataloading.__init__.py` file which seemed to fix the issue for me.
Please let me know if that works for you.
